# Most Used Functions in Graph Neural Networks (GNN)

Graph Neural Networks (GNNs) are a type of neural network designed to perform learning tasks on graph-structured data. They are used in various applications such as social network analysis, molecular chemistry, and recommendation systems. In this notebook, we will cover some of the most commonly used functions and techniques in GNNs using popular libraries such as PyTorch Geometric.

## 1. Graph Representation

Graphs are represented using nodes (vertices) and edges. In PyTorch Geometric, graphs are typically represented using the `Data` class.

In [3]:
# Example: Graph Representation using PyTorch Geometric
!pip install torch_geometric
from torch_geometric.data import Data
import torch

# Define the graph
edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

# Create the Data object
data = Data(x=x, edge_index=edge_index)
print(data)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.2/64.2 kB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 19.1 MB/s eta 0:00:00
Data(x=[3, 1], edge_index=[2, 4])


## 2. Graph Convolutional Network (GCN) Layer

The Graph Convolutional Network (GCN) layer is a fundamental building block of GNNs. It applies convolution operations on graph-structured data.

In [5]:
# Example: GCN Layer using PyTorch Geometric
from torch_geometric.nn import GCNConv

# Define the GCN layer
gcn = GCNConv(in_channels=1, out_channels=2)

# Apply the GCN layer
out = gcn(data.x, data.edge_index)
print(out)

tensor([[ 0.1881,  0.7039],
        [ 0.0000,  0.0000],
        [-0.1881, -0.7039]], grad_fn=<AddBackward0>)


## 3. Graph Attention Network (GAT) Layer

The Graph Attention Network (GAT) layer uses attention mechanisms to weigh the importance of neighboring nodes.

In [6]:
# Example: GAT Layer using PyTorch Geometric
from torch_geometric.nn import GATConv

# Define the GAT layer
gat = GATConv(in_channels=1, out_channels=2, heads=2)

# Apply the GAT layer
out = gat(data.x, data.edge_index)
print(out)

tensor([[ 0.1474,  0.0066,  0.0274,  0.1297],
        [ 0.0144,  0.0007, -0.0075, -0.0356],
        [-0.1368, -0.0062, -0.0328, -0.1553]], grad_fn=<AddBackward0>)


## 4. GraphSAGE Layer

GraphSAGE is a GNN layer that generates embeddings by sampling and aggregating features from a node's local neighborhood.

In [7]:
# Example: GraphSAGE Layer using PyTorch Geometric
from torch_geometric.nn import SAGEConv

# Define the GraphSAGE layer
sage = SAGEConv(in_channels=1, out_channels=2)

# Apply the GraphSAGE layer
out = sage(data.x, data.edge_index)
print(out)

tensor([[ 0.1337,  0.0333],
        [-0.7531, -0.5699],
        [-1.6400, -1.1731]], grad_fn=<AddBackward0>)


## 5. Pooling Layers

Pooling layers are used to coarsen the graph by reducing the number of nodes while preserving the graph structure.

In [8]:
# Example: Pooling Layer using PyTorch Geometric
from torch_geometric.nn import global_mean_pool

# Sample data for pooling
batch = torch.tensor([0, 0, 1], dtype=torch.long)

# Apply the pooling layer
pooled = global_mean_pool(out, batch)
print(pooled)

tensor([[-0.3097, -0.2683],
        [-1.6400, -1.1731]], grad_fn=<DivBackward0>)


## 6. Training a GNN Model

Training a GNN model involves defining a model class, a loss function, and an optimizer. The training loop iterates over the data and updates the model parameters.

In [9]:
# Example: Training a GNN Model using PyTorch Geometric
import torch.nn.functional as F
from torch_geometric.nn import GCNConv
from torch.optim import Adam

# Define the GNN model
class GNN(torch.nn.Module):
    def __init__(self):
        super(GNN, self).__init__()
        self.conv1 = GCNConv(in_channels=1, out_channels=2)
        self.conv2 = GCNConv(in_channels=2, out_channels=2)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        return x

# Initialize the model, loss function, and optimizer
model = GNN()
optimizer = Adam(model.parameters(), lr=0.01)
loss_fn = torch.nn.MSELoss()

# Sample training data
y = torch.tensor([[0], [1], [0]], dtype=torch.float)

# Training loop
model.train()
for epoch in range(20):
    optimizer.zero_grad()
    out = model(data.x, data.edge_index)
    loss = loss_fn(out, y)
    loss.backward()
    optimizer.step()

    print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1, Loss: 0.5715527534484863
Epoch 2, Loss: 0.548150360584259
Epoch 3, Loss: 0.5258955359458923
Epoch 4, Loss: 0.507640540599823
Epoch 5, Loss: 0.49011269211769104
Epoch 6, Loss: 0.4733084738254547
Epoch 7, Loss: 0.45722317695617676
Epoch 8, Loss: 0.44185081124305725
Epoch 9, Loss: 0.4271838665008545
Epoch 10, Loss: 0.4132134020328522
Epoch 11, Loss: 0.39992907643318176
Epoch 12, Loss: 0.38731908798217773
Epoch 13, Loss: 0.3753702640533447
Epoch 14, Loss: 0.3640683591365814
Epoch 15, Loss: 0.3533976972103119
Epoch 16, Loss: 0.3433417081832886
Epoch 17, Loss: 0.3338828384876251
Epoch 18, Loss: 0.3250025808811188
Epoch 19, Loss: 0.316681832075119
Epoch 20, Loss: 0.3089006543159485


/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([3, 1])) that is different to the input size (torch.Size([3, 2])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
